---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.16
  amd64: ghcr.io/home-assistant/amd64-base:3.16
  armhf: ghcr.io/home-assistant/armhf-base:3.16
  armv7: ghcr.io/home-assistant/armv7-base:3.16
  i386: ghcr.io/home-assistant/i386-base:3.16
# codenotary:
#   signer: notary@home-assistant.io
#   base_image: notary@home-assistant.io
# args:
  # CLI_VERSION: 4.21.0
  # LIBWEBSOCKETS_VERSION: 4.2.1
  # TTYD_VERSION: 3e37e33b1cd927ae8f25cfbcf0da268723b6d230
